### ISSUE TITLE
NFS share of ZFS volume: 'Stale file handle'

### ISSUE THREAD

**Issue by cnrd** [openzfsonosx/zfs#716]
Hi

Using v. 1.9.0

I'm sharing a zpool using NFS from macOS Mojave to debian 9.9

This is from /etc/exports on macOS
`/Volumes/tank -maproot=root:wheel -alldirs -network x.x.x.x -mask y.y.y.y`

This is from /etc/fstab on debian:
`x.x.x.x:/Volumes/tank /mnt/tank nfs vers=3 0 0` (also tried defaults)

If I try to do `touch test` I get this: `touch: setting times of 'test': Stale file handle` however the file is created `-rw-r--r-- 1 root root 0 Jun 16 01:02 test`.

The real problem is that other programs are misbehaving if they use that mountpoint for anything
Here is sabnzbd:
```
2019-06-16 01:06:02,121::INFO::[__init__:681] Adding Ubuntu-15.10-desktop-AMD64.nzb
2019-06-16 01:06:02,159::INFO::[misc:999] Creating directories: /downloads/intermediate/Ubuntu-15.10-desktop-AMD64
2019-06-16 01:06:02,198::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.10 - SABnzbd_nzf_qTXO78 added to queue
2019-06-16 01:06:02,200::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.11 - SABnzbd_nzf_M4SHDN added to queue
2019-06-16 01:06:02,218::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.12 - SABnzbd_nzf_DLYV0O added to queue
2019-06-16 01:06:02,238::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.13 - SABnzbd_nzf_FFlOMj added to queue
2019-06-16 01:06:02,276::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.14 - SABnzbd_nzf_JE0Lfg added to queue
2019-06-16 01:06:02,280::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.par2 - SABnzbd_nzf_cxqzbS added to queue
2019-06-16 01:06:02,296::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol000+01.par2 - SABnzbd_nzf_AtUOBO added to queue
2019-06-16 01:06:02,302::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol001+02.par2 - SABnzbd_nzf_oiyQ8m added to queue
2019-06-16 01:06:02,307::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol003+04.par2 - SABnzbd_nzf_1wkB5Q added to queue
2019-06-16 01:06:02,320::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol007+08.par2 - SABnzbd_nzf_qRn0fL added to queue
2019-06-16 01:06:02,332::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol015+16.par2 - SABnzbd_nzf_11zkkb added to queue
2019-06-16 01:06:02,347::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol031+32.par2 - SABnzbd_nzf_kALaMB added to queue
2019-06-16 01:06:02,361::INFO::[nzbstuff:530] File 6d7a0ed727cbb76648e7dc080ae5b704.vol063+37.par2 - SABnzbd_nzf_g0urev added to queue
2019-06-16 01:06:02,361::INFO::[__init__:624] Backing up /downloads/intermediate/Ubuntu-15.10-desktop-AMD64/__ADMIN__/Ubuntu-15.10-desktop-AMD64.nzb.gz
2019-06-16 01:06:02,375::ERROR::[__init__:633] Saving /downloads/intermediate/Ubuntu-15.10-desktop-AMD64/__ADMIN__/Ubuntu-15.10-desktop-AMD64.nzb.gz failed
2019-06-16 01:06:02,376::INFO::[__init__:634] Traceback:
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/__init__.py", line 631, in save_compressed
    f.close()
IOError: [Errno 13] Permission denied
2019-06-16 01:06:02,379::ERROR::[dirscanner:240] Error while adding Ubuntu-15.10-desktop-AMD64.nzb, removing
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/sabnzbd/dirscanner.py", line 223, in ProcessSingleFile
    nzo_info=nzo_info, url=url, reuse=reuse, dup_check=dup_check)
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 846, in __init__
    self.set_final_name_pw(name)
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 1357, in set_final_name_pw
    self.save_to_disk()
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 1837, in save_to_disk
    self.save_attribs()
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 1842, in save_attribs
    set_attrib_file(self.workpath, (self.cat, self.pp, self.script, self.priority, self.final_name, self.password, self.url))
  File "/usr/share/sabnzbdplus/sabnzbd/nzbstuff.py", line 2101, in set_attrib_file
    f.close()
IOError: [Errno 13] Permission denied
```
It seems like it is loosing the file handle which makes stuff not work?

Also I tried exporting my home folder which resides on an APFS volume, that worked fine and does not exhibit the above problems.

**Comment by lundman** [comment]
Sharing NFS on OSX and mounting on OSX at least works here.
```
172.16.248.128:/Volumes/tank   14Gi  204Ki   14Gi     1%      81            29457136    0%   /Volumes/test

# touch /Volumes/test/hello
-rw-r--r--  1 lundman  everyone  0 Jun 17 09:09 hello
```

But could be there are some differences when talking to debian. To track this down further, I think you should capture the error with tcpdump - but perhaps more revealing would be to turn on `sysctl kstat.zfs.darwin.tunable.vnop_debug=1` and watch the logs `log stream --source --predicate 'sender == "zfs" OR sender == "spl"' --style compact` as you trigger the failure.

**Comment by cnrd** [comment]
Here are some logs:
`sudo touch hello` where hello does not exist (result in: `touch: setting times of 'hello': Stale file handle`)
```
Timestamp               Ty Process[PID:TID]
2019-06-17 07:04:58.630 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup 'hello'
2019-06-17 07:04:58.630 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_lookup> Negative-cache made for 'hello'
2019-06-17 07:04:58.630 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 2 : dvp 4 'hello'
2019-06-17 07:04:58.631 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup 'hello'
2019-06-17 07:04:58.631 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup -2 : dvp 4 'hello'
2019-06-17 07:04:58.631 Df kernel[0:98d2b] (zfs) <zfs`zfs_vnop_create> vnop_create: 'hello'
2019-06-17 07:04:58.631 Df kernel[0:98d2b] (zfs) <zfs`zfs_znode_getvnode> getvnode zp <private> with vp 0x0 zfsvfs <private> vfs <private>
2019-06-17 07:04:58.631 Df kernel[0:98d2b] (zfs) <zfs`zfs_znode_getvnode> Assigned zp <private> with vp <private>
2019-06-17 07:04:58.671 Df kernel[0:99007] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup '.store.db'
2019-06-17 07:04:58.671 Df kernel[0:99007] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 261 '.store.db'
2019-06-17 07:04:58.672 Df kernel[0:99007] (zfs) <zfs`zfs_vnop_ioctl> vnop_ioctl 0000002c: VTYPE 1
2019-06-17 07:04:58.672 Df kernel[0:99007] (zfs) <zfs`zfs_vnop_ioctl> zfs_vnop_ioctl F_RDADVISE
```

`sudo touch hello` after running `cd .. cd safe` (otherwise no logs and keeps complaning about stale file handle)
```
2019-06-17 07:06:57.751 Df kernel[0:98d29] (zfs) <zfs`zfs_vnop_setattr> vnop_setattr: called on vp <private> with mask 6000, err=0
2019-06-17 07:06:58.766 Df kernel[0:9903f] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.766 Df kernel[0:990c2] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.766 Df kernel[0:9903f] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 0 size 32
2019-06-17 07:06:58.766 Df kernel[0:990c2] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 0 size 32
2019-06-17 07:06:58.771 Df kernel[0:990c3] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 4 '.VolumeIcon.icns'
2019-06-17 07:06:58.771 Df kernel[0:990c3] (zfs) <zfs`zfs_vnop_inactive> vnop_inactive: zp <private> vp <private> type 1
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup 'hello'
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 4 'hello'
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 93 size 32
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_listxattr> +listxattr vp <private>:
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 93 size 32
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.ResourceFork'
2019-06-17 07:06:58.922 Df kernel[0:990bb] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 93 size 0
2019-06-17 07:06:58.924 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 4 'hello'
2019-06-17 07:06:58.924 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_inactive> vnop_inactive: zp <private> vp <private> type 1
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 0 size 32
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_getxattr> +getxattr vp <private>: 'com.apple.FinderInfo'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_getxattr> -getxattr vp <private> : 0 size 32
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup '.localized'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> Negative-cache made for '.localized'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 2 : dvp 4 '.localized'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup '.DS_Store'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> Negative-cache made for '.DS_Store'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 2 : dvp 4 '.DS_Store'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 2 : dvp 4 '.DS_Store'
2019-06-17 07:06:58.925 Df kernel[0:97da7] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 2 : dvp 4 '.DS_Store'
2019-06-17 07:06:58.927 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup 'tmp.spotlight.state'
2019-06-17 07:06:58.927 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 131 'tmp.spotlight.state'
2019-06-17 07:06:58.927 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_setattr> vnop_setattr: called on vp <private> with mask 0010, err=0
2019-06-17 07:06:58.927 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_setattr> ZFS: setattr new size 0 0
2019-06-17 07:06:58.927 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_write> zfs_vnop_write(vp <private>, offset 0x0 size 0x1000
2019-06-17 07:06:58.954 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_inactive> vnop_inactive: zp <private> vp <private> type 1
2019-06-17 07:06:58.954 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup '.store.db'
2019-06-17 07:06:58.955 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 131 '.store.db'
2019-06-17 07:06:58.955 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_write> zfs_vnop_write(vp <private>, offset 0x0 size 0x1000
2019-06-17 07:06:58.961 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> vnop_ioctl 00000033: VTYPE 1
2019-06-17 07:06:58.961 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> zfs_vnop_ioctl F_FULLFSYNC
2019-06-17 07:06:58.962 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> zfs_vnop_ioctl F_BARRIERFSYNC
2019-06-17 07:06:58.981 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 131 'tmp.spotlight.state'
2019-06-17 07:06:58.982 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_setattr> vnop_setattr: called on vp <private> with mask 0010, err=0
2019-06-17 07:06:58.982 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_setattr> ZFS: setattr new size 0 0
2019-06-17 07:06:58.982 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_write> zfs_vnop_write(vp <private>, offset 0x0 size 0x1000
2019-06-17 07:06:59.007 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_inactive> vnop_inactive: zp <private> vp <private> type 1
2019-06-17 07:06:59.007 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> +vnop_lookup 'live.0.indexHead'
2019-06-17 07:06:59.007 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_lookup> -vnop_lookup 0 : dvp 131 'live.0.indexHead'
2019-06-17 07:06:59.007 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_write> zfs_vnop_write(vp <private>, offset 0x0 size 0x10
2019-06-17 07:06:59.013 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> vnop_ioctl 00000033: VTYPE 1
2019-06-17 07:06:59.013 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> zfs_vnop_ioctl F_FULLFSYNC
2019-06-17 07:06:59.013 Df kernel[0:9908c] (zfs) <zfs`zfs_vnop_ioctl> zfs_vnop_ioctl F_BARRIERFSYNC
```

**Comment by cnrd** [comment]
@lundman anything else I can try? :-)

**Comment by lundman** [comment]
Usually NFS is all about `zfs_vfs_vget()` which is outside of the print with debug. If you are able to compile your own version, I would suggest adding `#define dprintf printf` near the top of `module/zfs/zfs_vfsops.c`. 

Otherwise, we could check what the call returns using `dtrace`; ie:

```
# dtrace -n 'zfs_vfs_vget:entry { printf("ino: %lld", arg1);}' -n 'zfs_vfs_vget:return { printf("%d", arg1);} '
```

**Comment by cnrd** [comment]
I'm pretty sure I have compiled a version with that define, but I'm not seeing anything with `sudo log stream --source --predicate 'sender == "zfs" OR sender == "spl"' --style compact`
